name: Build & push to gh-pages branch

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Build
      run: |
        yarn install
        npm run build.p
        
    - name: Update branch
      run: |
        mv public/ ../
        git checkout gh-pages
        mv .git/ ../public/.git
        cd ../public
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "generated"
